baseurl = "https://www.fabianehlert.com/"
languageCode = "en-us"
title = "Fabian Ehlert"
theme = "casper"
paginate = 10
DisqusShortname = "Fabian Ehlert"
Copyright = "All rights reserved - 2019"

[params]
  description = "...developing & designing stuff out of Milky Way Galaxy."
  logo = "images/essential/me.circle.png"
  cover = "images/essential/cover.jpg"
  author = "Fabian Ehlert"
  authorlocation = "Dresden, Germany"
  authorwebsite = "https://fabianehlert.com"
  # bio = "My bio"
  githubName = "fabianehlert"
  twitterName = "fabianehlert"
  # linkedinName = "https://de.linkedin.com/in/fabianehlert"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  [[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/"

  [[menu.main]]
    name = "Projects"
    weight = 90
    identifier = "projects"
    url = "/projects"

  [[menu.main]]
    name = "About me"
    weight = 80
    identifier = "about"
    url = "/about"

  [[menu.main]]
    name = "Imprint"
    url = "/imprint"
    weight = 60
