baseurl = "https://www.fabianehlert.com/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"
Copyright = "Copyright © 2020 Fabian Ehlert. All rights reserved."

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"

# navigation
[menu]

  # Header

  [[menu.header]]
  name = "Photos"
  URL = "https://photos.fabianehlert.com"
  weight = 2

  [[menu.header]]
  name = "Curriculum Vitae"
  URL = "https://fabianehlert.com/cv.pdf"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "mailto:hello@fabianehlert.com"
  weight = 4

  # Footer

  [[menu.footer]]
  name = "Curriculum Vitae"
  URL = "https://fabianehlert.com/cv.pdf"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "mailto:hello@fabianehlert.com"
  weight = 3

  [[menu.footer]]
  name = "Imprint"
  URL = "https://fabianehlert.com/imprint.html"
  weight = 4


[params]

  sections = ["showcase"]

  [params.logo]
    text1 = "Fabian Ehlert"

  [params.footer]
      copyright = "Copyright © 2020 Fabian Ehlert. All rights reserved."
